pipeline {
    agent any
    environment {
        PATH = "/opt/apache-maven-3.8.6/bin:$PATH"
    }
    stages {
        stage("clone code") {
            steps {
                git credentialsId: 'githublogin', branch: 'main', url: 'https://github.com/Ajayalla/jenkins-pipeline-example.git'
            }
        }
        stage("build code") {
            steps {
                sh "cd my-app"
                sh "mvn clean build"
                sh "fuser -k 8080/tcp"
                sh "cd /var/lib/jenkins/workspace/Java Project1/my-app/"
                sh "nohup java -jar gateway-0.0.1-SNAPSHOT.jar &"
               // sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}
