pipeline {
    agent any
    environment {
        PATH = "/opt/apache-maven-3.6.0/bin:$PATH"
    }
    stages {
        stage("clone code") {
            steps {
                git credentialsId: 'githublogin', branch: 'main', url: 'https://github.com/Ajayalla/jenkins-pipeline-example.git'
            }
        }
        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/Java-Project1/my-app") {
                sh 'mvn -B -DskipTests clean package'
                }
            
            }
        }
     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   } 
}
